// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsIzhV2Qz6QM2BE34y7p5enkDhy_XOHjI',
    appId: '1:1036289352099:web:6b140bc1c30ffd21f1ba16',
    messagingSenderId: '1036289352099',
    projectId: 'cleanarchtechflutter',
    authDomain: 'cleanarchtechflutter.firebaseapp.com',
    storageBucket: 'cleanarchtechflutter.appspot.com',
    measurementId: 'G-5T7E1JSTJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX0Z-Lj02KO1SODQFCxlqV9CtvFUuSYy8',
    appId: '1:1036289352099:android:3a798066d8f376eaf1ba16',
    messagingSenderId: '1036289352099',
    projectId: 'cleanarchtechflutter',
    storageBucket: 'cleanarchtechflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPNg7-h7r20R4f7WRta8vKYMmRXg1BzhI',
    appId: '1:1036289352099:ios:24017a4925850e74f1ba16',
    messagingSenderId: '1036289352099',
    projectId: 'cleanarchtechflutter',
    storageBucket: 'cleanarchtechflutter.appspot.com',
    iosClientId: '1036289352099-83lpngflhp1eqk7e7nhjoo10uklt1ido.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPNg7-h7r20R4f7WRta8vKYMmRXg1BzhI',
    appId: '1:1036289352099:ios:24017a4925850e74f1ba16',
    messagingSenderId: '1036289352099',
    projectId: 'cleanarchtechflutter',
    storageBucket: 'cleanarchtechflutter.appspot.com',
    iosClientId: '1036289352099-83lpngflhp1eqk7e7nhjoo10uklt1ido.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate',
  );
}
